download it when real version.
bazelbuild/setup-bazelisk pull request #121
Opened 2023-10-27 05:45 UTC by kekxv

https://github.com/bazelbuild/setup-bazelisk/issues/120

2023-10-27 14:46 UTC, mishas requested changes
Wouldn't it just be simpler to ask Gitea users to create a GitHub token and pass it in manually?

2023-10-27 14:46 UTC, mishas commented on src/installer.ts
>    const auth = `token ${token}`;
If I understand correctly the difference between GitHub and Gitea, then the `${token}` parameter here will be empty.
As such, instead of the code changes below you can probably just make the following change here:
```suggestion
  const auth = token ? `token ${token}` : undefined;
```

Please test this, as I'm not sure what comes in `${token}` in Gitea.

2023-10-27 14:46 UTC, mishas commented on src/installer.ts
> +    if (versionSpec.indexOf('x') === -1 && versionSpec.split(".").length === 3) {
There're multiple problems with this code being here:
1. This doesn't take into account all different ways versions can be specified. For example, what if `versionSpec == ">=1.0.0"`?
2. This use direct download when version is exact - but it also means that it will not use the token to download on GitHub which might hit a call limit or throttling (and as such make this worse for GitHub users)

Additionally, I think it's important to note (in a comment) that:
1. This is a patch for Gitea, which doesn't have GitHub tokens
4. The Gitea version only works with exact versions, not semver evaluations.

2023-10-27 14:54 UTC, kekxv commented on src/installer.ts
>    const auth = `token ${token}`;
`${token}` not empty or null. `${token}`, and it was not `github token`, currently(`Oct 27 2023`) cannot be customized.

2023-10-27 15:01 UTC, kekxv commented on src/installer.ts
> +    if (versionSpec.indexOf('x') === -1 && versionSpec.split(".").length === 3) {
What you said makes sense, but I'm not very familiar with this area.  Perhaps you can help me with this issue when you have time: **When the full version is passed in, no longer query via GitHub token**

(你说的很有道理，只是我对这方面不是很熟悉，也许你有空的时候可以帮忙处理这个问题：当传入完整版本的情况下，不再通过github token查询)

> This is the translated content.  If there are any objections, you can check the original text.

2024-03-11 11:24 UTC, junyer commented
Closing this PR because this repository is about to be archived.

2024-03-11 11:24 UTC, closed without merging